<fieldset class="fieldset myclass">
    <div class="field required">
        <label class="label"
               for="json_out"><span><?php echo $block->escapeHtml(__('Output')) ?></span></label>
        <div class="input-box control">
            <input name="json_out" id="json_out" title="<?php echo $block->escapeHtml(__('Output')) ?>"
                   value='Put valid json here, e.g. {"a":1,"b":2,"c":3,"d":4,"e":5}' class="input-text required-entry"
                   type="text">
        </div>
    </div>
    <div class="field">
        <div class="primary">
            <button type="submit" class="action submit primary btn_put_json"><span>Put Json Data</span></button>
        </div>
    </div>
</fieldset>
<script>
    require(
        [
            'jquery'
        ],
        function (
            $
        ) {
            $('body').on('click', '.btn_put_json', function () {

                var url = "<?php echo $block->getUrl() . 'module/Index/Debug' ?>";
                var value = $("input[name='json_out']").val()

                try {

                    $.ajax({
                        url: url,
                        type: 'POST',
                        dataType: 'json',
                        showLoader: true,
                        data: {'data': value},
                        success: function (data) {
                            var json = JSON.parse(data);
                            $("#json_out").val(json.data);
                            alert(`Data you sent is: ${json.data}`)
                        }
                    });
                } catch (e) {
                }
            });
        });

</script>
